import type { Lecture, LectureRegistration, LectureAttendance } from "@/types/lecture"

export const mockLectures: Lecture[] = [
  {
    id: "1",
    title: {
      en: "Digital Safety for Children",
      ar: "الأمان الرقمي للأطفال",
    },
    description: {
      en: "Learn how to protect your children in the digital world. This workshop covers online safety, privacy settings, and healthy screen time habits.",
      ar: "تعلم كيفية حماية أطفالك في العالم الرقمي. يغطي هذا الورشة السلامة عبر الإنترنت وإعدادات الخصوصية وعادات وقت الشاشة الصحية.",
    },
    speaker: "Dr. Sarah Johnson",
    speakerRole: "Child Psychologist & Digital Safety Expert",
    dateTime: "2026-06-15T14:00:00Z",
    duration: 120,
    location: "Main Conference Hall, DSC Building",
    meetingLink: "https://zoom.us/j/example123",
    maxParticipants: 50,
    thumbnail: "/images/lecture-digital-safety.jpg",
    status: "published",
    created: "2026-05-01T10:00:00Z",
    updated: "2026-05-01T10:00:00Z",
  },
  {
    id: "2",
    title: {
      en: "Understanding Autism Spectrum",
      ar: "فهم طيف التوحد",
    },
    description: {
      en: "A comprehensive session on understanding autism, early signs, and support strategies for parents and educators.",
      ar: "جلسة شاملة حول فهم التوحد والعلامات المبكرة واستراتيجيات الدعم للآباء والمعلمين.",
    },
    speaker: "Dr. Ahmed Hassan",
    speakerRole: "Developmental Pediatrician",
    dateTime: "2026-06-20T16:00:00Z",
    duration: 90,
    location: "Room 302, DSC Building",
    maxParticipants: 30,
    thumbnail: "/images/lecture-autism.jpg",
    status: "published",
    created: "2026-05-02T10:00:00Z",
    updated: "2026-05-02T10:00:00Z",
  },
  {
    id: "3",
    title: {
      en: "Positive Parenting Techniques",
      ar: "تقنيات الأبوة والأمومة الإيجابية",
    },
    description: {
      en: "Learn evidence-based positive parenting strategies to build strong relationships with your children while setting healthy boundaries.",
      ar: "تعلم استراتيجيات الأبوة والأمومة الإيجابية القائمة على الأدلة لبناء علاقات قوية مع أطفالك مع وضع حدود صحية.",
    },
    speaker: "Ms. Fatima Al-Rashid",
    speakerRole: "Certified Parenting Coach",
    dateTime: "2026-06-25T10:00:00Z",
    duration: 150,
    location: "Virtual - Zoom",
    meetingLink: "https://zoom.us/j/example456",
    maxParticipants: 100,
    status: "published",
    created: "2026-05-03T10:00:00Z",
    updated: "2026-05-03T10:00:00Z",
  },
  {
    id: "4",
    title: {
      en: "Learning Disabilities 101",
      ar: "أساسيات صعوبات التعلم",
    },
    description: {
      en: "An introductory session on identifying and supporting children with learning disabilities. Covers dyslexia, dyscalculia, and more.",
      ar: "جلسة تمهيدية حول تحديد ودعم الأطفال ذوي صعوبات التعلم. تغطي عسر القراءة وعسر الحساب والمزيد.",
    },
    speaker: "Dr. Michael Chen",
    speakerRole: "Special Education Specialist",
    dateTime: "2026-05-10T14:00:00Z",
    duration: 120,
    location: "Main Conference Hall, DSC Building",
    maxParticipants: 40,
    status: "completed",
    created: "2026-04-15T10:00:00Z",
    updated: "2026-04-15T10:00:00Z",
  },
  {
    id: "5",
    title: {
      en: "ADHD Management Strategies",
      ar: "استراتيجيات إدارة ADHD",
    },
    description: {
      en: "Practical strategies for managing ADHD at home and school. Includes behavioral techniques and organizational tools.",
      ar: "استراتيجيات عملية لإدارة ADHD في المنزل والمدرسة. تشمل التقنيات السلوكية وأدوات التنظيم.",
    },
    speaker: "Dr. Layla Mahmoud",
    speakerRole: "Child & Adolescent Psychiatrist",
    dateTime: "2026-07-05T15:00:00Z",
    duration: 180,
    location: "Auditorium A, DSC Building",
    maxParticipants: 60,
    status: "draft",
    created: "2026-05-04T10:00:00Z",
    updated: "2026-05-04T10:00:00Z",
  },
]

export const mockRegistrations: LectureRegistration[] = [
  {
    id: "1",
    lectureId: "4",
    userId: "user1",
    userName: "Ahmad Abdullah",
    email: "ahmad@example.com",
    phone: "+971501234567",
    registeredAt: "2026-04-20T08:30:00Z",
    status: "attended",
  },
  {
    id: "2",
    lectureId: "4",
    userId: "user2",
    userName: "Sarah Smith",
    email: "sarah@example.com",
    registeredAt: "2026-04-21T14:15:00Z",
    status: "attended",
  },
  {
    id: "3",
    lectureId: "4",
    userId: "user3",
    userName: "Mohammed Ali",
    email: "mohammed@example.com",
    registeredAt: "2026-04-22T09:00:00Z",
    status: "cancelled",
  },
  {
    id: "4",
    lectureId: "1",
    userId: "user1",
    userName: "Ahmad Abdullah",
    email: "ahmad@example.com",
    phone: "+971501234567",
    registeredAt: "2026-05-05T10:00:00Z",
    status: "registered",
  },
  {
    id: "5",
    lectureId: "1",
    userId: "user4",
    userName: "Layla Hassan",
    email: "layla@example.com",
    registeredAt: "2026-05-06T11:30:00Z",
    status: "registered",
  },
  {
    id: "6",
    lectureId: "2",
    userId: "user2",
    userName: "Sarah Smith",
    email: "sarah@example.com",
    registeredAt: "2026-05-07T09:15:00Z",
    status: "registered",
  },
]

export const mockAttendance: LectureAttendance[] = [
  {
    registrationId: "1",
    attended: true,
    attendedAt: "2026-05-10T14:05:00Z",
  },
  {
    registrationId: "2",
    attended: true,
    attendedAt: "2026-05-10T14:02:00Z",
  },
]
